"""add constraint

Revision ID: 39586ab511f1
Revises: 87ee68089239
Create Date: 2026-02-04 17:08:30.293884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39586ab511f1'
down_revision: Union[str, Sequence[str], None] = '87ee68089239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('books_orders_book_id_fkey'), 'books_orders', type_='foreignkey')
    op.drop_constraint(op.f('books_orders_order_id_fkey'), 'books_orders', type_='foreignkey')
    op.create_foreign_key(None, 'books_orders', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'books_orders', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books_orders', type_='foreignkey')
    op.drop_constraint(None, 'books_orders', type_='foreignkey')
    op.create_foreign_key(op.f('books_orders_order_id_fkey'), 'books_orders', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(op.f('books_orders_book_id_fkey'), 'books_orders', 'books', ['book_id'], ['id'])
    # ### end Alembic commands ###
