"""update user with password hash field

Revision ID: 4a2b9c434675
Revises: 9b5febf1d430
Create Date: 2026-02-05 23:11:54.605967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a2b9c434675'
down_revision: Union[str, Sequence[str], None] = '9b5febf1d430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('authors', sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'is_superuser')
    op.drop_column('authors', 'is_active')
    # ### end Alembic commands ###
