"""add constraint

Revision ID: 87ee68089239
Revises: 192c8f9b3cce
Create Date: 2026-02-03 16:50:33.577973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87ee68089239'
down_revision: Union[str, Sequence[str], None] = '192c8f9b3cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('idx_unique_book_order', 'books_orders', ['book_id', 'order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('idx_unique_book_order', 'books_orders', type_='unique')
    # ### end Alembic commands ###
