"""update user with password hash field

Revision ID: 9b5febf1d430
Revises: 75bff8c15a12
Create Date: 2026-02-05 23:06:11.601512

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9b5febf1d430"
down_revision: Union[str, Sequence[str], None] = "75bff8c15a12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("authors", sa.Column("password_hash", sa.String(length=200), nullable=True))
    op.execute(
        """
        UPDATE authors
        SET password_hash = '$2b$12$invalidinitialhashinvalidinitialhashxx'
        """
    )
    op.alter_column("authors", "password_hash", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("authors", "password_hash")
    # ### end Alembic commands ###
