"""add author model with relation

Revision ID: ef4678b1efb9
Revises: 8d6427d41e84
Create Date: 2026-02-02 15:05:14.116365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef4678b1efb9'
down_revision: Union[str, Sequence[str], None] = '8d6427d41e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('image_file', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_authors_id'), 'authors', ['id'], unique=False)
    op.add_column('books', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'author_id')
    op.drop_index(op.f('ix_authors_id'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
